@startuml Use cases

title Варианты использования системы (верхнеуровневые)

left to right direction

actor "Гость" as Guest

usecase "Регистрация пользователя" as Registration
usecase "Редактирование профиля пользователя" as EditProfile

Guest -> Registration
Registration ..> EditProfile : include

actor "Пользователь" as User
actor "Expert" as Expert

Expert -left-|> User
User -> EditProfile

usecase "Создать план участка" as CreatePlan
User -> CreatePlan
(Указать базовый план) .up.> CreatePlan : extends

User -> (Изменить план своего участка)
User -> (Участвовать в консультации)
Expert -> (Участвовать в консультации)
Expert -> (Согласиться на консультацию)

actor "Интернет магазин" as InternetStore
User -> (Получить рекомендации)
InternetStore -up-> (Получить рекомендации)

@enduml
