@startuml Auth

title Авторизация пользователя

actor :Пользователь: as User

usecase (Авторизация через смс) as AuthBySms
usecase (Авторизация по паролю) as AuthByPassword

User --> AuthBySms
User --> AuthByPassword

@enduml
