@startuml AuthBySms

title Авторизация по смс

actor "Пользователь" as User
boundary "Страница планирования участка" as Page
database "База планов участков" as DB

User --> Page ++ : кнопка показать рекомендации
Page --> DB ++ :

entity "План как будет" as PlanToBe
entity "План как есть" as PlanAsIs

DB --> PlanToBe **:
DB --> PlanAsIs **:

Page <-- DB --

Page --> User : индикатор прогресса

create control "Расчет рекомендаций" as Calcalator

Page --> Calcalator ++: new

Calcalator --> PlanToBe ++: найти новые постройки
Calcalator <-- PlanToBe --
Calcalator --> PlanToBe ++: найти новые зоны
Calcalator <-- PlanToBe --

Calcalator --> Calcalator ++: расчет материалов и инструментов
deactivate Calcalator

Calcalator --> Calcalator ++: расчет материалов, инструментов и саженцев
deactivate Calcalator

participant "Интернет магазин" as InternetStore
Calcalator --> InternetStore ++: получить цены
Calcalator <-- InternetStore --

Calcalator --> Calcalator ++: сформировать список рекомендаций
deactivate Calcalator

Calcalator --> Page
destroy Calcalator

Page --> User : результаты

@enduml

' (*) --> "Click -> Вход по смс"
' "Click -> Вход по смс" --> "Появилась форма для входа по смс"
' "Появилась форма для входа по смс" --> "Click -> Получить код"
' "Click -> Получить код" --> "Ошибка - введите номер телефона"
' "Появилась форма для входа по смс" --> "Вводим номер телефона"
' "Вводим номер телефона" --> "Click -> Получить код"
' "Click -> Получить код" --> "Вводим смс-код"
' "Вводим смс-код" --> "Click -> Вход в систему"
' "Click -> Вход в систему" --> (*)
' note left
'     Авторизовались
'     в системе
' end note

' @enduml
