@startuml AuthByPassword

title Авторизация пользователя по паролю

(*) --> "Click -> Вход по паролю"
"Click -> Вход по паролю" --> "Появилась форма для входа по паролю"
"Появилась форма для входа по паролю" --> "Вводим номер телефона"
"Вводим номер телефона" --> "Вводим пароль"
"Вводим пароль" --> "Click -> Вход в систему"
"Click -> Вход в систему" --> (*)
note left
    Авторизовались
    в системе
end note

@enduml
