// Иконки приложения
export default {
  ARROWS_SYNCHRONIZE: 'arrowsSynchronize',
  CLOSE: 'close',
  COG: 'cog',
  CONTENT_ARCHIVE_LOCKER: 'contentArchiveLocker',
  FILE_CLIPBOARD: 'fileClipboard',
  FNS: 'fns',
  FRII: 'frii',
  INNOVATION: 'innovation',
  LOGO: 'logo',
  LOGO2: 'logo2',
  MONEY_CASH_BILL1: 'moneyCashBill1',
  NOTE_PAD_TEXT: 'notePadText',
  PLUS_CIRCLE_PRIMARY: 'plusCirclePrimary',
  PROFESSIONS_MAN_CONSTRUCTION1: 'professionsManConstruction1',
  PROFESSIONS_MAN_CONSTRUCTION2: 'professionsManConstruction2',
  RUS_PO: 'rusPo',
  SEARCH: 'search',
  SECURITY_SHIELD_PERSON: 'securityShieldPerson',
  SETTING_MENU2: 'settingMenu2',
  SKOLKOVO: 'skolkovo',
  USER_ADD: 'userAdd',
  USER_CHECK: 'userCheck',
  USER_EDIT: 'userEdit',
  USER_FULL_BODY: 'userFullBody',
  USER_LOCKED: 'userLocked',
  USER_MULTIPLE: 'userMultiple',
  VALIDATION_CHECK: 'validationCheck',
  VISIBILITY: 'visibility',
  VISIBILITY_OFF: 'visibility_off',
}
